# -*- coding: utf-8 -*-
"""Python Hackathon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ze4DqkiTqXUwSbgBUa0oBIGh82udJ4lr
"""

from google.colab import files
uploaded = files.upload()

"""**IMPORTING DATA AND LIBRARIES**"""

import pandas as pd
import numpy as np
df = pd.read_csv("PS10_Dataset_10.csv")

"""**DATA** **UNDERSTANDING**"""

df.head()

df.tail()

df.info()

df.shape

df.describe()

"""DATA **MANIPULATION**"""

df["Total"] = df[["A","B","C","D"]].sum(axis=1)

"""DATA **ANALYSIS**"""

print("Mean:\n", df.mean(numeric_only=True))
print("Max:\n", df.max(numeric_only=True))
print("Min:\n", df.min(numeric_only=True))

"""**DATA** **VISUALISATION**"""

import matplotlib.pyplot as plt
x=range(len(df))
plt.figure(figsize=(20,8))
plt.plot(x,df['Total'],marker="o",color="green")
plt.title("Students Performance")
plt.xlabel("Students")
plt.ylabel("Total Marks")
plt.show()

plt.hist(df['Total'],bins=10,edgecolor="black")
plt.title("Marks Distribution")
plt.xlabel("Marks")
plt.ylabel("Frequency")
plt.show()

top_student = df["Total"].idxmax()
low_student = df["Total"].idxmin()
print("\nInsights:\n")
print(f"{top_student} is the top performer.")
print(f"{low_student} needs improvement.")