# -*- coding: utf-8 -*-
"""PythonCS1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19esPY9SUSlK3wSeMtT69P_OCj99r8u02
"""

import random
def number_guessing_game():
  print("Game Start")
  num=random.randint(0,100)
  attempts=0
  guess=-1
  while(guess!=num):
    guess=int(input("Guess No.: "))
    attempts+=1
    if(guess>num):
      print("High")
    elif(guess<num):
      print("Low")
    else:
      print(f"Congratulations! You guess the number in {attempts} attempts")
      print("Game Over!")
      break
number_guessing_game()