# -*- coding: utf-8 -*-
"""PythonCS2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PjeZ2ZjV6ryO6MiSOD_GV9RpKxihq9uD
"""

import random
def word_scramble_game():
  words=["school","college","python","teacher","professor","uniform","machine","university","notebook","blackboard"]
  word=random.choice(words)
  scramble=list(word)
  random.shuffle(scramble)
  scrambled_word="".join(scramble)
  print("Scrambled word :",scrambled_word)
  attempts_allowed = 3
  score = 0
  attempts=attempts_allowed
  while attempts > 0 :
    guess=input("Guess the word : ")
    if guess == word :
      print("Yeah! You win")
      score+=1
      break
    else :
      attempts-=1
      if attempts>0:
        print(f"Wrong! Attempts left : {attempts}")
      else:
        print("You lose! No attempts left")
        print("Game over")
        print(f"The correct word was : {word}")
  print("Game over")
  print(f"Your final score : {score}")
word_scramble_game()