# -*- coding: utf-8 -*-
"""PythonCS4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H4lJ2in6bGTNzcDCaNnqmGcwOEW-RX-m
"""

FILE_NAME = "tasks (1).txt"

# Add Task
def add_task():
    desc = input("Enter task description: ")
    status = "Pending"

    with open(FILE_NAME, "r") as file:
        lines = file.readlines()
        if lines:
            last_id = int(lines[-1].split("|")[0])
            task_id = last_id + 1
        else:
            task_id = 1

    with open(FILE_NAME, "a") as file:
        file.write(f"{task_id}|{desc}|{status}\n")

    print("Task added successfully!")

# View Tasks
def view_tasks():
    with open(FILE_NAME, "r") as file:
        lines = file.readlines()
        if not lines:
            print("No tasks found.")
            return

        for line in lines:
            task_id, desc, status = line.strip().split("|",2)
            print(f"ID: {task_id} | {desc} | {status}")

# Update Task
def update_task():
    task_id = input("Enter Task ID to update: ")

    with open(FILE_NAME, "r") as file:
        lines = file.readlines()

    with open(FILE_NAME, "w") as file:
        found = False
        for line in lines:
            t_id, desc, status = line.strip().split("|",2)

            if t_id == task_id:
                found = True
                print("1. Update Description")
                print("2. Mark as Completed")
                choice = input("Choose option: ")

                if choice == "1":
                    desc = input("Enter new description: ")
                elif choice == "2":
                    status = "Completed"

            file.write(f"{t_id}|{desc}|{status}\n")

    if found:
        print("Task updated!")
    else:
        print("Task not found.")

# Delete Task
def delete_task():
    task_id = input("Enter Task ID to delete: ")

    with open(FILE_NAME, "r") as file:
        lines = file.readlines()

    with open(FILE_NAME, "w") as file:
        found = False
        for line in lines:
            t_id, desc, status = line.strip().split("|",2)

            if t_id != task_id:
                file.write(line)
            else:
                found = True

    if found:
        print("Task deleted!")
    else:
        print("Task not found.")

# Main Menu
def main():
    while True:
        print("\n--- TO-DO NOTES BUILDER ---")
        print("1. Add Task")
        print("2. View Tasks")
        print("3. Update Task")
        print("4. Delete Task")
        print("5. Exit")

        choice = input("Enter choice: ")

        if choice == "1":
            add_task()
        elif choice == "2":
            view_tasks()
        elif choice == "3":
            update_task()
        elif choice == "4":
            delete_task()
        elif choice == "5":
            print("Exiting...")
            break
        else:
            print("Invalid choice!")

if __name__ == "__main__":
    main()