# -*- coding: utf-8 -*-
"""PythonCS5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJMdLOSRWi2Jri8_ub6n2PACRXVUNtFj
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# -------------------------------
# Step 1: Create Student Data
# -------------------------------
data = {
    "Name": ["Aman", "Riya", "Karan", "Neha", "Rahul"],
    "Math": [85, 90, 78, 92, 70],
    "Science": [88, 76, 85, 95, 65],
    "English": [90, 85, 80, 88, 72]
}

df = pd.DataFrame(data)

# -------------------------------
# Step 2: Calculate Total & Average
# -------------------------------
df["Total"] = df[["Math", "Science", "English"]].sum(axis=1)
df["Average"] = df["Total"] / 3

print("\n Student Data:\n")
print(df)

# -------------------------------
# Step 3: Statistical Analysis
# -------------------------------
print("\n Statistical Analysis:\n")
print("Mean:\n", df.mean(numeric_only=True))
print("\nMedian:\n", df.median(numeric_only=True))
print("\nStandard Deviation:\n", df.std(numeric_only=True))

# -------------------------------
# Step 4: Identify Performers
# -------------------------------
top_student = df.loc[df["Total"].idxmax()]
low_student = df.loc[df["Total"].idxmin()]

print("\n Top Performer:")
print(f"{top_student['Name']} with total marks {top_student['Total']}")

print("\n Lowest Performer:")
print(f"{low_student['Name']} with total marks {low_student['Total']}")

# -------------------------------
# Step 5: Subject-wise Comparison
# -------------------------------
subject_avg = df[["Math", "Science", "English"]].mean()

print("\n Subject-wise Average Marks:\n")
print(subject_avg)

# -------------------------------
# Step 6: Visualization
# -------------------------------

# Bar Graph
plt.figure()
subject_avg.plot(kind='bar')
plt.title("Subject-wise Average Marks")
plt.xlabel("Subjects")
plt.ylabel("Marks")
plt.show()

# Line Plot
plt.figure()
df.set_index("Name")[["Math", "Science", "English"]].plot(marker='o')
plt.title("Student Performance Across Subjects")
plt.ylabel("Marks")
plt.show()

# Histogram
plt.figure()
df["Total"].plot(kind='hist')
plt.title("Distribution of Total Marks")
plt.xlabel("Total Marks")
plt.show()

# -------------------------------
# Step 7: Insights (Dynamic)
# -------------------------------
print("\n Insights:\n")
print(f"- {top_student['Name']} is the top performer.")
print(f"- {low_student['Name']} needs improvement.")

highest_subject = subject_avg.idxmax()
lowest_subject = subject_avg.idxmin()

print(f"- {highest_subject} has the highest average marks.")
print(f"- {lowest_subject} has the lowest average marks.")